[advisories]
yanked = "warn"
ignore = [
    # "RUSTSEC-XXXX-YYYY"
]

[licenses]
allow = ["Apache-2.0", "MIT", "ISC", "Unicode-DFS-2016", "BSD-3-Clause", "OpenSSL"]
confidence-threshold = 0.8
exceptions = []

[[licenses.clarify]]
crate = "ring"
expression = "OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
multiple-versions = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
